#!/usr/bin/env node

/*
  Download README files from a GitHub repo and store in a
  local directory as HTML and Markdown, optionally compressing
  the directory as a .zip file.

  By Johan Brook, 2014
*/

var Github = require('github'),
    Q = require('q'),
    fs = require('q-io/fs'),
    markdown = require('marked'),
    createArchive = require('./package')

if(process.env.GH_TOKEN === undefined) {
  console.log("No GH_TOKEN provided.")
  process.exit(0)
}

var details = {
  user: "introprogramming",
  repo: "exercises",
  target: "exercises"
}

var gh = new Github({
  version: "3.0.0"
})

var fetchContent = function(path) {
  var getContent = Q.denodeify(gh.repos.getContent)

  return getContent({
    user: details.user,
    repo: details.repo,
    path: path
  })
}

var fetchExercises = function() {
  return fetchContent("exercises")
}

var writeExercise = function(fileName, content) {
  return fs.write(details.target + "/" + fileName, content)
}

var fetchReadmeas = function() {
  return fs.makeTree(details.target)
  .then(fetchExercises)
  .then(function(exercises) {
    return Q.all(exercises.map(function(ex) {

      return fetchContent(ex.path+"/README.md")
        .then(function(readme) {
          var buf = new Buffer(readme.content, 'base64')

          return Q.all([
            writeExercise(ex.name+".md", buf.toString()),
            writeExercise(ex.name+".html", markdown(buf.toString()))
          ])
        })
    }))
  })
}

var init = function() {
  console.log("Usage: node import [--zip]")
  var archive = process.argv[2] !== undefined && process.argv[2] === '--zip'

  gh.authenticate({
    type: "oauth",
    token: process.env.GH_TOKEN
  })

  var p = fetchReadmeas()
  .then(function(dirs) {
    console.log(dirs.length + " exercises fetched and saved to /"+details.target)
    return details.target
  })

  if(archive) {
    p.then(function(dir) {
      return createArchive(dir).then(function(files) {
        console.log('Created '+dir+'.zip, with '+ files.length+' files.')
        return files
      })
    })
  }

  p.catch(function(err) {
    console.error(err)
  })
}

// Detect if we're being called directly or require()'d

if(require.main === module) {
  init()
}
else {
  module.exports = fetchReadmeas
}
