#!/usr/bin/env node

var zip = require('node-zip')(),
    Q = require('q'),
    fs = require('q-io/fs'),
    path = require('path')



var createArchive = function(dir) {
  var folder = zip.folder(dir)

  return fs.list(dir)
  .then(function(files) {
    return Q.all(files.map(function(file) {
      return fs.read(path.join(dir, file), 'b')
      .then(function(content) {
        return folder.file(file, content)
      })
    }))
  })
  .then(function() {
    var data = zip.generate({
      base64: false,
      compression: 'DEFLATE',
      type: 'nodebuffer'
    })

    return fs.write(path.basename(dir)+'.zip', data, 'wb')
  })
}


var init = function() {
  if(process.argv[2] === undefined) {
    console.log("Usage: node package <path/to/dir>")
    return process.exit(0)
  }

  var dir = process.argv[2]

  return createArchive(dir)
    .then(function() {
      console.log('Created '+dir+'.zip')
    })
    .catch(function(err) {
      console.error(err)
    })
}


init()
